//! Effects collection for vim-core.
//!
//! A collection of effects with builder pattern for fluent construction.
//!
//! Simple push-and-return builder methods are generated by the
//! [`define_effect_builders!`] macro in `builder_macros.rs`.
//! Methods with custom logic (e.g. `impl Into<CompactString>`, conditional
//! pushes, hardcoded fields) remain handwritten here.
//!
//! # Typestate Undo Architecture
//!
//! `Effects` uses a typestate parameter to enforce undo group discipline at
//! compile time:
//!
//! ```text
//! Effects<Closed>  ──begin_undo()──►  Effects<UndoOpen>  ──end_undo()──►  Effects<Closed>
//!                                          │
//!                                          │ begin_insert()
//!                                          ▼
//!                                     Effects<InsertPending>
//! ```
//!
//! Text mutations (`insert`, `delete`, `replace`) are only callable in
//! `UndoOpen` state. `begin_insert()` is only callable in `UndoOpen` state.
//! This makes the original bug (`Effects<Closed>.begin_insert()`) a compile error.

use crate::effects::effect::SourceContext;
use crate::effects::info_message::{InfoMessage, LineModCounts};
use crate::effects::Effect;
use crate::primitives::{
    Diagnostic, Direction, LineNumber, MotionType, Offset, Range, RegisterName, SelectionShape,
    SubstitutePreviewMatch, VirtualTextPosition,
};
use compact_str::CompactString;
use smallvec::SmallVec;
use std::marker::PhantomData;

/// Sealed marker traits and types for the undo typestate.
pub mod undo_state {
    mod sealed {
        /// Sealed trait — only the three marker types implement it.
        pub trait EffectState {}
    }
    pub use sealed::EffectState;

    /// No undo group is open. Text mutations are forbidden.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Closed;
    /// An undo group is open. Text mutations are allowed.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct UndoOpen;
    /// An undo group is open and insert mode entry has been emitted.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct InsertPending;

    impl sealed::EffectState for Closed {}
    impl sealed::EffectState for UndoOpen {}
    impl sealed::EffectState for InsertPending {}
}

/// A collection of effects.
///
/// Uses `SmallVec` for stack allocation in the common case (≤4 effects).
/// Most normal-mode commands produce 3-4 effects (cursor + mode + undo).
/// The reduced inline capacity (4 vs 8) halves the struct size while still
/// covering ~90% of commands without heap allocation.
///
/// The type parameter `S` tracks the undo group state at compile time.
/// Default is `Closed` — no undo group is open.
#[must_use = "Effects represent side-effects that must be applied"]
pub struct Effects<S: undo_state::EffectState = undo_state::Closed> {
    pub(super) inner: SmallVec<[Effect; 4]>,
    _state: PhantomData<S>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Transition helper (private)
// ─────────────────────────────────────────────────────────────────────────────

impl<S: undo_state::EffectState> Effects<S> {
    /// Change the typestate marker without touching the inner vec.
    #[inline]
    fn transition<T: undo_state::EffectState>(self) -> Effects<T> {
        Effects {
            inner: self.inner,
            _state: PhantomData,
        }
    }

    /// Erase the typestate and return `Effects<Closed>`.
    ///
    /// Used at the boundary where typestate has done its job and the raw
    /// effects need to be handed to `CommandResult` / `Response`.
    #[inline]
    pub(crate) fn into_raw_closed(self) -> Effects<undo_state::Closed> {
        Effects {
            inner: self.inner,
            _state: PhantomData,
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Generic impl (all states)
// ─────────────────────────────────────────────────────────────────────────────

impl<S: undo_state::EffectState> Effects<S> {
    /// Add a raw effect. `pub(crate)` to prevent external consumers from
    /// bypassing the typestate (use the typed builder methods instead).
    #[inline]
    pub(crate) fn push(&mut self, effect: Effect) {
        self.inner.push(effect);
    }

    /// Number of effects.
    #[inline]
    #[must_use]
    pub fn len(&self) -> usize {
        self.inner.len()
    }

    /// Check if empty.
    #[inline]
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    /// Access effects as a slice.
    #[inline]
    #[must_use]
    pub fn as_slice(&self) -> &[Effect] {
        &self.inner
    }

    /// Access effects as a mutable slice. `pub(crate)` to prevent external
    /// bypass of the typestate.
    #[inline]
    pub(crate) fn as_mut_slice(&mut self) -> &mut [Effect] {
        &mut self.inner
    }

    /// Consume and return the inner `SmallVec`.
    #[inline]
    #[must_use]
    pub fn into_inner(self) -> SmallVec<[Effect; 4]> {
        self.inner
    }

    /// Consume and return as `Vec<Effect>`.
    #[inline]
    #[must_use]
    pub fn into_vec(self) -> Vec<Effect> {
        self.inner.into_vec()
    }

    /// Iterate over effects.
    #[inline]
    pub fn iter(&self) -> impl Iterator<Item = &Effect> {
        self.inner.iter()
    }

    /// Drain all effects.
    #[inline]
    pub fn drain(&mut self) -> impl Iterator<Item = Effect> + '_ {
        self.inner.drain(..)
    }

    /// Extend with effects from any iterator of `Effect`. `pub(crate)` to
    /// prevent external bypass of the typestate.
    ///
    /// Accepts `Effects`, `Vec<Effect>`, `SmallVec<[Effect; N]>`, slices, etc.
    #[inline]
    pub(crate) fn extend(&mut self, other: impl IntoIterator<Item = Effect>) {
        self.inner.extend(other);
    }

    // ═══════════════════════════════════════════════════════════════════
    // Handwritten builders (custom logic / impl Into<CompactString>)
    // State-agnostic: these don't mutate document content.
    // ═══════════════════════════════════════════════════════════════════

    /// Set last find command with resolved case flags for `;` and `,` repeat.
    #[inline]
    #[must_use]
    pub fn set_last_find_with_case(
        mut self,
        direction: crate::primitives::FindDirection,
        target_char: char,
        ignorecase: bool,
        smartcase: bool,
    ) -> Self {
        self.inner.push(Effect::SetLastFind {
            direction,
            target_char,
            sneak_c2: None,
            resolved_ignorecase: ignorecase,
            resolved_smartcase: smartcase,
        });
        self
    }

    /// Set last find command for sneak repeat (`;` and `,`).
    #[inline]
    #[must_use]
    pub fn set_last_find_sneak(
        mut self,
        direction: crate::primitives::FindDirection,
        c1: char,
        c2: char,
    ) -> Self {
        self.inner.push(Effect::SetLastFind {
            direction,
            target_char: c1,
            sneak_c2: Some(c2),
            resolved_ignorecase: false,
            resolved_smartcase: false,
        });
        self
    }

    /// Set last find command for sneak repeat with resolved case flags.
    #[inline]
    #[must_use]
    pub fn set_last_find_sneak_with_case(
        mut self,
        direction: crate::primitives::FindDirection,
        c1: char,
        c2: char,
        ignorecase: bool,
        smartcase: bool,
    ) -> Self {
        self.inner.push(Effect::SetLastFind {
            direction,
            target_char: c1,
            sneak_c2: Some(c2),
            resolved_ignorecase: ignorecase,
            resolved_smartcase: smartcase,
        });
        self
    }

    /// Set a register's content.
    ///
    /// # Linewise invariant
    ///
    /// When `motion_type` is `LineWise`, a trailing `\n` is appended if the
    /// text does not already end with one. This matches Neovim's `op_yank`
    /// behavior and ensures the invariant is enforced at the Effect level
    /// so all consumers (engine effect processor, test runners) see
    /// canonical linewise content.
    pub fn set_register(
        mut self,
        name: RegisterName,
        text: impl Into<CompactString>,
        motion_type: MotionType,
    ) -> Self {
        let mut text = text.into();
        if motion_type == MotionType::LineWise && !text.ends_with('\n') {
            text.push('\n');
        }
        self.inner.push(Effect::SetRegister {
            name,
            text,
            motion_type,
        });
        self
    }

    /// Set the search pattern and direction (`/`, `?`, `*`, `#`).
    #[inline]
    pub fn set_search_pattern(
        mut self,
        pattern: impl Into<CompactString>,
        direction: Direction,
    ) -> Self {
        self.inner.push(Effect::SetSearchPattern {
            pattern: pattern.into(),
            direction,
        });
        self
    }

    /// Set the last substitute replacement string (for `~` in patterns and replacements).
    #[inline]
    pub fn set_last_substitute(mut self, replacement: impl Into<CompactString>) -> Self {
        self.inner.push(Effect::SetLastSubstitute {
            replacement: replacement.into(),
        });
        self
    }

    /// Store the flags used by the last `:s` command (for `:&&` repeat-with-flags).
    ///
    /// Carries the full [`SubFlags`](crate::primitives::SubFlags) struct directly
    /// (see [`Effect::SetLastSubstituteFlags`]).
    #[inline]
    pub fn set_last_substitute_flags(mut self, flags: crate::primitives::SubFlags) -> Self {
        self.inner.push(Effect::SetLastSubstituteFlags { flags });
        self
    }

    /// Set the substitute pattern (Neovim's `RE_SUBST`) and mark it as most recently used.
    ///
    /// Emitted by `:s/pattern/replacement/` when an explicit pattern is given.
    #[inline]
    pub fn set_substitute_pattern(mut self, pattern: impl Into<CompactString>) -> Self {
        self.inner.push(Effect::SetSubstitutePattern {
            pattern: pattern.into(),
        });
        self
    }

    /// Execute normal-mode keystrokes on each line in range (`:norm`).
    #[inline]
    pub fn norm_command(
        mut self,
        start_line: LineNumber,
        end_line: LineNumber,
        keys: impl Into<CompactString>,
        remap: bool,
    ) -> Self {
        self.inner.push(Effect::NormCommand {
            start_line,
            end_line,
            keys: keys.into(),
            remap,
        });
        self
    }

    /// Show a message in the status bar (free-text convenience wrapper).
    #[inline]
    pub fn show_message(mut self, text: impl Into<CompactString>) -> Self {
        self.inner.push(Effect::ShowInfo {
            info: InfoMessage::Text(text.into()),
        });
        self
    }

    /// Emit an audible or visual bell.
    #[inline]
    pub fn bell(mut self) -> Self {
        self.inner.push(Effect::Bell);
        self
    }

    /// Show a structured informational message.
    #[inline]
    pub fn show_info(mut self, info: InfoMessage) -> Self {
        self.inner.push(Effect::ShowInfo { info });
        self
    }

    /// Show a line modification report.
    #[inline]
    pub fn show_line_report(self, counts: LineModCounts) -> Self {
        self.show_info(InfoMessage::LineReport(counts))
    }

    /// Show a verbose-only message.
    #[inline]
    pub fn show_verbose(self, message: impl Into<CompactString>) -> Self {
        self.show_info(InfoMessage::Verbose(message.into()))
    }

    /// Show an error with source file/line context (for `:source` script errors).
    #[inline]
    pub fn show_error_with_source(
        mut self,
        error: crate::errors::VimError,
        source: SourceContext,
    ) -> Self {
        self.inner.push(Effect::ShowError {
            error,
            source: Some(source),
        });
        self
    }

    /// Invoke a host-registered action by name (`<Action>(name)` bridge).
    #[inline]
    pub fn host_action(mut self, name: impl Into<CompactString>) -> Self {
        self.inner.push(Effect::HostAction { name: name.into() });
        self
    }

    /// Copy text to system clipboard (`"+y`).
    #[inline]
    pub fn copy_to_clipboard(
        mut self,
        text: impl Into<CompactString>,
        register: RegisterName,
    ) -> Self {
        self.inner.push(Effect::CopyToClipboard {
            text: text.into(),
            register,
        });
        self
    }

    /// Preview substitute matches (inccommand).
    #[inline]
    pub fn substitute_preview(mut self, matches: Vec<SubstitutePreviewMatch>) -> Self {
        self.inner.push(Effect::SubstitutePreview { matches });
        self
    }

    /// Clear the substitute preview.
    #[inline]
    pub fn clear_substitute_preview(mut self) -> Self {
        self.inner.push(Effect::ClearSubstitutePreview);
        self
    }

    /// Show the next match for interactive `:s///c` confirmation.
    #[inline]
    pub fn substitute_confirm_show(
        mut self,
        match_range: Range,
        replacement: impl Into<CompactString>,
        match_index: u32,
        total_matches: u32,
    ) -> Self {
        self.inner.push(Effect::SubstituteConfirmShow {
            match_range,
            replacement: replacement.into(),
            match_index,
            total_matches,
        });
        self
    }

    /// End the interactive substitute confirm session.
    #[inline]
    pub fn substitute_confirm_end(mut self) -> Self {
        self.inner.push(Effect::SubstituteConfirmEnd);
        self
    }

    /// Store substitute confirm state (engine-internal, consumed by effect processor).
    #[inline]
    pub fn set_substitute_confirm_state(
        mut self,
        payload: crate::primitives::SubstituteConfirmPayload,
    ) -> Self {
        self.inner.push(Effect::SetSubstituteConfirmState {
            payload: Box::new(payload),
        });
        self
    }

    /// Clear substitute confirm state (engine-internal, consumed by effect processor).
    #[inline]
    pub fn clear_substitute_confirm_state(mut self) -> Self {
        self.inner.push(Effect::ClearSubstituteConfirmState);
        self
    }

    /// Place virtual text at a specific buffer position.
    #[inline]
    pub fn set_virtual_text(
        mut self,
        namespace: u32,
        line: LineNumber,
        col: Offset,
        text: impl Into<CompactString>,
        position: VirtualTextPosition,
    ) -> Self {
        self.inner.push(Effect::SetVirtualText {
            namespace,
            line,
            col,
            text: text.into(),
            position,
        });
        self
    }

    /// Clear all virtual text in the given namespace.
    #[inline]
    pub fn clear_virtual_text(mut self, namespace: u32) -> Self {
        self.inner.push(Effect::ClearVirtualText { namespace });
        self
    }

    /// Synchronize syntax-based fold ranges with the host.
    #[inline]
    pub fn sync_fold_ranges(mut self, ranges: Vec<(LineNumber, LineNumber)>) -> Self {
        self.inner.push(Effect::SyncFoldRanges { ranges });
        self
    }

    /// Set the full list of diagnostics for a namespace.
    #[inline]
    pub fn set_diagnostics(mut self, namespace: u32, diagnostics: Vec<Diagnostic>) -> Self {
        self.inner.push(Effect::SetDiagnostics {
            namespace,
            diagnostics,
        });
        self
    }

    /// Emit a complete undo tree snapshot for visualization (`:undotree`).
    #[inline]
    pub fn undo_tree_snapshot(mut self, snapshot: crate::primitives::UndoTreeSnapshot) -> Self {
        self.inner.push(Effect::UndoTreeSnapshot { snapshot });
        self
    }

    /// Set visual selection and position cursor at the selection head.
    ///
    /// Emits `SetSelection` followed by `SetCursor(head)`, satisfying the
    /// effect pairing contract required by shell dispatch layers.
    ///
    /// The ordering is load-bearing: `SetSelection` **must** appear before
    /// `SetCursor` — the dispatch layer uses this to suppress redundant
    /// caret movement when a selection is active.
    ///
    /// Prefer this over separate `set_selection()` + `set_cursor()` calls
    /// for visual/select mode transitions.
    #[inline]
    pub fn set_visual_selection(
        mut self,
        anchor: Offset,
        head: Offset,
        shape: SelectionShape,
    ) -> Self {
        self.inner.push(Effect::SetSelection {
            anchor,
            head,
            shape,
        });
        self.inner.push(Effect::SetCursor { offset: head });
        self
    }

    // ═══════════════════════════════════════════════════════════════════
    // Validation
    // ═══════════════════════════════════════════════════════════════════

    /// Validate that all `BeginUndoGroup` / `EndUndoGroup` markers are correctly paired.
    ///
    /// Used in `debug_assert!` by the effect processor to catch builder bugs early.
    ///
    /// # Errors
    ///
    /// Returns `Err` with a description if groups are mismatched:
    /// - `"EndUndoGroup without matching BeginUndoGroup"` — extra close
    /// - `"BeginUndoGroup without matching EndUndoGroup"` — unclosed group
    pub fn validate_undo_groups(&self) -> Result<(), &'static str> {
        validate_undo_groups_slice(&self.inner)
    }

    /// Validate ordering invariants on this effects builder.
    ///
    /// Delegates to the standalone [`validate_ordering`] function.
    ///
    /// # Errors
    ///
    /// Returns the first [`OrderingError`] found, if any.
    pub fn validate_ordering(&self) -> Result<(), OrderingError> {
        validate_ordering(&self.inner)
    }

    // ═══════════════════════════════════════════════════════════════════
    // Optimization
    // ═══════════════════════════════════════════════════════════════════

    /// Optimize the effects list by removing redundant effects.
    ///
    /// This is called by the engine after command execution to minimize
    /// the number of effects the host needs to process.
    ///
    /// Optimizations performed:
    /// 1. Deduplicate trailing `SetCursor` effects (after all text edits),
    ///    keeping only the last one.
    /// 2. Remove `ClearMessage` when immediately followed by `ShowInfo`.
    /// 3. Coalesce consecutive `ShowInfo` effects, keeping only the last
    ///    in each run.
    pub fn optimize(&mut self) {
        Self::optimize_vec(&mut self.inner);
        debug_assert!(
            self.validate_ordering().is_ok(),
            "Effects ordering invariant violated after optimize(): {:?}",
            self.validate_ordering().err()
        );
    }

    /// Optimize a `SmallVec<[Effect; 4]>` in-place.
    ///
    /// Same rules as [`optimize`](Self::optimize). Shared by both `Effects`
    /// (via `optimize()`) and `Response` (via direct call on its SmallVec).
    pub fn optimize_vec(effects: &mut SmallVec<[Effect; 4]>) {
        let len = effects.len();
        if len < 2 {
            return;
        }

        // Find the index of the last text edit (or None if no edits).
        let last_edit_idx = effects.iter().rposition(|e| {
            matches!(
                e,
                Effect::Insert { .. } | Effect::Delete { .. } | Effect::Replace { .. }
            )
        });

        // Find the last trailing SetCursor (the one we keep; all earlier ones go).
        let trailing_start = last_edit_idx.map_or(0, |i| i + 1);
        let last_trailing_cursor = effects.get(trailing_start..).and_then(|slice| {
            slice
                .iter()
                .rposition(|e| matches!(e, Effect::SetCursor { .. }))
                .map(|rel| rel + trailing_start)
        });

        // Build a keep-mask in a single forward pass.
        // Uses SmallVec to avoid heap allocation for typical effect counts (≤32).
        let mut keep: SmallVec<[bool; 32]> = smallvec::smallvec![true; len];
        for (i, (flag, effect)) in keep.iter_mut().zip(effects.iter()).enumerate() {
            // Rule 0: Strip Noop effects (produced by insert+delete annihilation).
            if matches!(effect, Effect::Noop) {
                *flag = false;
                continue;
            }
            // Rule 1: Remove redundant trailing SetCursor effects.
            if i >= trailing_start
                && matches!(effect, Effect::SetCursor { .. })
                && Some(i) != last_trailing_cursor
            {
                *flag = false;
                continue;
            }
            // Rule 2 & 3: Message coalescing (peek ahead).
            if let Some(next) = effects.get(i + 1) {
                if matches!(
                    (effect, next),
                    (Effect::ClearMessage, Effect::ShowInfo { .. })
                        | (Effect::ShowInfo { .. }, Effect::ShowInfo { .. })
                ) {
                    *flag = false;
                }
            }
        }

        // Compact in-place: retain only kept elements.
        debug_assert_eq!(
            keep.len(),
            effects.len(),
            "keep mask length mismatch in optimize_vec"
        );
        let mut keep_iter = keep.into_iter();
        effects.retain(|_| keep_iter.next().unwrap_or(false));
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Effects<Closed> — no undo group open
// ─────────────────────────────────────────────────────────────────────────────

impl Effects<undo_state::Closed> {
    /// Create an empty effects collection.
    #[inline]
    pub fn new() -> Self {
        Self {
            inner: SmallVec::new(),
            _state: PhantomData,
        }
    }

    /// Create with a single effect.
    #[inline]
    pub fn single(effect: Effect) -> Self {
        let mut effects = SmallVec::new();
        effects.push(effect);
        Self {
            inner: effects,
            _state: PhantomData,
        }
    }

    /// Begin an undo group.
    #[inline]
    pub fn begin_undo(mut self) -> Effects<undo_state::UndoOpen> {
        self.inner.push(Effect::BeginUndoGroup {
            cursor_strategy: crate::primitives::UndoCursorStrategy::FirstEdit,
        });
        self.transition()
    }

    /// Begin an undo group that restores cursor to pre-command position.
    #[inline]
    pub fn begin_undo_force_entry(mut self) -> Effects<undo_state::UndoOpen> {
        self.inner.push(Effect::BeginUndoGroup {
            cursor_strategy: crate::primitives::UndoCursorStrategy::EntryPosition,
        });
        self.transition()
    }

    /// Wrap in `BeginUndoGroup`/`EndUndoGroup` if any edit effects are present.
    ///
    /// An "edit" is any effect that mutates document content: `Insert`, `Delete`,
    /// or `Replace`. This is a convenience for ex commands (`:s`, `:g`, `:j`) that
    /// may or may not produce edits depending on whether patterns matched.
    /// Commands that always produce edits should use `begin_undo()`/`end_undo()`
    /// directly for clarity.
    ///
    /// If the effects already contain undo group markers (e.g. from sub-commands
    /// like `:g/pat/sort` that manage their own groups), wrapping is skipped
    /// entirely to avoid double-nesting.
    pub fn undo_wrap(self) -> Self {
        // If effects already contain undo group markers (from sub-commands
        // like `:g/pat/sort`), skip wrapping to avoid double-nesting.
        let already_wrapped = self.inner.iter().any(|e| {
            matches!(
                e,
                Effect::BeginUndoGroup { .. } | Effect::EndUndoGroup { .. }
            )
        });
        if already_wrapped {
            return self;
        }
        let has_edits = self.inner.iter().any(|e| {
            matches!(
                e,
                Effect::Insert { .. } | Effect::Delete { .. } | Effect::Replace { .. }
            )
        });
        if has_edits {
            // Build a new SmallVec with BeginUndoGroup first, existing effects,
            // then EndUndoGroup. Avoids the O(n) memmove of insert(0).
            let mut wrapped = SmallVec::with_capacity(self.inner.len() + 2);
            wrapped.push(Effect::BeginUndoGroup {
                cursor_strategy: crate::primitives::UndoCursorStrategy::FirstEdit,
            });
            wrapped.extend(self.inner);
            wrapped.push(Effect::EndUndoGroup { node_id: None });
            Self {
                inner: wrapped,
                _state: PhantomData,
            }
        } else {
            self
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    // Crate-internal text mutation methods on Closed state.
    //
    // Many internal helper functions build partial effect lists
    // (e.g., insert_text_and_advance, newline_with_indent) that are
    // composed into already-open undo groups by callers.  These helpers
    // don't manage undo groups themselves — they just produce edit effects.
    //
    // Making these pub(crate) preserves the public API invariant
    // (external callers must open an undo group before mutating) while
    // allowing internal code to continue working unchanged.
    // ═══════════════════════════════════════════════════════════════════

    /// Insert text at byte offset (crate-internal, for partial effect builders).
    #[inline]
    pub(crate) fn insert(mut self, offset: Offset, text: impl Into<CompactString>) -> Self {
        self.inner.push(Effect::Insert {
            offset,
            text: text.into(),
        });
        self
    }

    /// Delete a byte range (crate-internal, for partial effect builders).
    #[inline]
    pub(crate) fn delete(mut self, range: Range) -> Self {
        self.inner.push(Effect::Delete { range });
        self
    }

    /// Replace a byte range with new text (crate-internal, for partial effect builders).
    #[inline]
    pub(crate) fn replace(mut self, range: Range, text: impl Into<CompactString>) -> Self {
        self.inner.push(Effect::Replace {
            range,
            text: text.into(),
        });
        self
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Effects<UndoOpen> — undo group is open, text mutations allowed
// ─────────────────────────────────────────────────────────────────────────────

impl Effects<undo_state::UndoOpen> {
    /// Create an `UndoOpen` effects collection for resuming an open undo group.
    ///
    /// Used by `exit_finalize` which needs to emit `end_undo()` for a group
    /// that was opened earlier (during insert entry).
    #[inline]
    pub(crate) fn resume_open() -> Self {
        Self {
            inner: SmallVec::new(),
            _state: PhantomData,
        }
    }

    /// End an undo group.
    #[inline]
    pub fn end_undo(mut self) -> Effects<undo_state::Closed> {
        self.inner.push(Effect::EndUndoGroup { node_id: None });
        self.transition()
    }

    /// Begin insert mode with full context.
    #[inline]
    pub fn begin_insert(
        mut self,
        entry_type: crate::primitives::InsertEntryType,
        count: u32,
        auto_indent_len: usize,
        entry_offset: Offset,
    ) -> Effects<undo_state::InsertPending> {
        self.inner.push(Effect::BeginInsert {
            entry_type,
            count,
            auto_indent_len,
            entry_offset,
        });
        self.transition()
    }

    /// Insert text at byte offset.
    #[inline]
    pub fn insert(mut self, offset: Offset, text: impl Into<CompactString>) -> Self {
        self.inner.push(Effect::Insert {
            offset,
            text: text.into(),
        });
        self
    }

    /// Delete a byte range.
    #[inline]
    pub fn delete(mut self, range: Range) -> Self {
        self.inner.push(Effect::Delete { range });
        self
    }

    /// Replace a byte range with new text.
    #[inline]
    pub fn replace(mut self, range: Range, text: impl Into<CompactString>) -> Self {
        self.inner.push(Effect::Replace {
            range,
            text: text.into(),
        });
        self
    }
}

/// Error describing a violation of effect ordering invariants.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum OrderingError {
    /// A text edit (Insert/Delete/Replace) appears after the last `SetCursor`
    /// with no subsequent cursor update.
    EditAfterFinalCursor,
    /// An undo group contains no edits.
    EmptyUndoGroup,
    /// Mismatched undo group brackets.
    UndoGroupMismatch,
}

impl std::fmt::Display for OrderingError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EditAfterFinalCursor => f.write_str(
                "text edit appears after the last SetCursor with no subsequent cursor update",
            ),
            Self::EmptyUndoGroup => {
                f.write_str("undo group contains no text edits (Insert/Delete/Replace)")
            }
            Self::UndoGroupMismatch => {
                f.write_str("mismatched BeginUndoGroup / EndUndoGroup brackets")
            }
        }
    }
}

impl std::error::Error for OrderingError {}

/// Validate that effects follow the canonical ordering invariants.
///
/// Invariants checked:
/// 1. **Undo groups bracket edits**: every `BeginUndoGroup`/`EndUndoGroup`
///    pair contains at least one text edit (Insert/Delete/Replace).
/// 2. **Undo group pairing**: matched Begin/End markers.
/// 3. **SetCursor follows all edits**: the last `SetCursor` must appear
///    after the last text edit (if any text edits exist).
///
/// This is intentionally a validation tool, not an enforcement mechanism.
/// The engine does NOT call this automatically — it exists for:
/// - Unit tests asserting correct effect sequences
/// - Debug builds (via `debug_assert!`)
/// - Host-side validation in development
///
/// # Errors
///
/// Returns the first invariant violation found, if any.
pub fn validate_ordering(effects: &[Effect]) -> Result<(), OrderingError> {
    validate_undo_group_pairing_and_content(effects)?;
    validate_cursor_after_edits(effects)
}

/// Check undo group pairing and that each group contains at least one edit.
fn validate_undo_group_pairing_and_content(effects: &[Effect]) -> Result<(), OrderingError> {
    let mut edit_stack: Vec<bool> = Vec::new();
    for effect in effects {
        match effect {
            Effect::BeginUndoGroup { .. } => {
                edit_stack.push(false);
            }
            Effect::EndUndoGroup { .. } => {
                if edit_stack.is_empty() {
                    return Err(OrderingError::UndoGroupMismatch);
                }
                // Safety: checked `!edit_stack.is_empty()` above.
                let Some(_had_edit) = edit_stack.pop() else {
                    unreachable!("edit_stack is non-empty");
                };
                // Empty undo groups are valid — the engine records them intentionally
                // (matching Neovim behavior) for cursor-only operations.
                // Propagate: inner group's edits count for the outer group.
                if let Some(top) = edit_stack.last_mut() {
                    *top = true;
                }
            }
            Effect::Insert { .. } | Effect::Delete { .. } | Effect::Replace { .. } => {
                if let Some(top) = edit_stack.last_mut() {
                    *top = true;
                }
            }
            _ => {}
        }
    }
    if !edit_stack.is_empty() {
        return Err(OrderingError::UndoGroupMismatch);
    }
    Ok(())
}

/// Check that the last `SetCursor` appears after the last text edit.
fn validate_cursor_after_edits(effects: &[Effect]) -> Result<(), OrderingError> {
    let mut last_edit_idx: Option<usize> = None;
    let mut last_cursor_idx: Option<usize> = None;
    for (i, effect) in effects.iter().enumerate() {
        match effect {
            Effect::Insert { .. } | Effect::Delete { .. } | Effect::Replace { .. } => {
                last_edit_idx = Some(i);
            }
            Effect::SetCursor { .. } => {
                last_cursor_idx = Some(i);
            }
            _ => {}
        }
    }
    if let (Some(edit_idx), Some(cursor_idx)) = (last_edit_idx, last_cursor_idx) {
        if edit_idx > cursor_idx {
            return Err(OrderingError::EditAfterFinalCursor);
        }
    }
    Ok(())
}

/// Validate that all `BeginUndoGroup` / `EndUndoGroup` markers are correctly paired.
///
/// Works on any `&[Effect]` slice — usable both by `Effects::validate_undo_groups`
/// and by callers that hold a `Vec<Effect>` (e.g. `effect_processor`).
///
/// # Errors
///
/// Returns `Err` with a static description if groups are mismatched:
/// - `"EndUndoGroup without matching BeginUndoGroup"` — extra close
/// - `"BeginUndoGroup without matching EndUndoGroup"` — unclosed group
pub fn validate_undo_groups_slice(effects: &[Effect]) -> Result<(), &'static str> {
    let mut depth: i32 = 0;
    for effect in effects {
        match effect {
            Effect::BeginUndoGroup { .. } => depth += 1,
            Effect::EndUndoGroup { .. } => {
                depth -= 1;
                if depth < 0 {
                    return Err("EndUndoGroup without matching BeginUndoGroup");
                }
            }
            _ => {}
        }
    }
    if depth != 0 {
        return Err("BeginUndoGroup without matching EndUndoGroup");
    }
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Trait implementations
// ─────────────────────────────────────────────────────────────────────────────

impl<S: undo_state::EffectState> std::fmt::Debug for Effects<S> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Effects")
            .field("inner", &self.inner)
            .finish()
    }
}

impl<S: undo_state::EffectState> Clone for Effects<S> {
    fn clone(&self) -> Self {
        Self {
            inner: self.inner.clone(),
            _state: PhantomData,
        }
    }
}

impl<S: undo_state::EffectState> PartialEq for Effects<S> {
    fn eq(&self, other: &Self) -> bool {
        self.inner == other.inner
    }
}

impl Default for Effects<undo_state::Closed> {
    fn default() -> Self {
        Self::new()
    }
}

impl<S: undo_state::EffectState> IntoIterator for Effects<S> {
    type Item = Effect;
    type IntoIter = smallvec::IntoIter<[Effect; 4]>;

    fn into_iter(self) -> Self::IntoIter {
        self.inner.into_iter()
    }
}

impl<'a, S: undo_state::EffectState> IntoIterator for &'a Effects<S> {
    type Item = &'a Effect;
    type IntoIter = std::slice::Iter<'a, Effect>;

    fn into_iter(self) -> Self::IntoIter {
        self.inner.iter()
    }
}

impl FromIterator<Effect> for Effects {
    fn from_iter<I: IntoIterator<Item = Effect>>(iter: I) -> Self {
        Self {
            inner: iter.into_iter().collect(),
            _state: PhantomData,
        }
    }
}

/// Implement `From<SmallVec<[Effect; N]>>` for common inline sizes.
macro_rules! impl_from_smallvec {
    ($($n:literal),+) => {$(
        impl From<SmallVec<[Effect; $n]>> for Effects {
            #[inline]
            fn from(v: SmallVec<[Effect; $n]>) -> Self {
                Self { inner: v.into_iter().collect(), _state: PhantomData }
            }
        }
    )+};
}

impl_from_smallvec!(2, 3, 4, 8);

/// Macro for creating effects inline.
#[macro_export]
macro_rules! effects {
    () => { $crate::effects::Effects::new() };
    ($($effect:expr),+ $(,)?) => {{
        let mut effects = $crate::effects::Effects::new();
        $(effects.push($effect);)+
        effects
    }};
}

#[cfg(test)]
#[path = "effects_tests.rs"]
mod tests;
